<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows10.0.22621.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>C:\Users\ogryz\Desktop\WebSite\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>4</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>01F395F2A3F49BE2D3B801CE07447E26A38F22AF</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>ApkaJezykowa_1_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>true</SignManifests>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Fonts\Montserrat-Italic-VariableFont_wght.ttf" />
    <Resource Include="Fonts\Montserrat-VariableFont_wght.ttf" />
    <Resource Include="Fonts\static\Montserrat-Black.ttf" />
    <Resource Include="Fonts\static\Montserrat-BlackItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-Bold.ttf" />
    <Resource Include="Fonts\static\Montserrat-BoldItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-ExtraBold.ttf" />
    <Resource Include="Fonts\static\Montserrat-ExtraBoldItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-ExtraLight.ttf" />
    <Resource Include="Fonts\static\Montserrat-ExtraLightItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-Italic.ttf" />
    <Resource Include="Fonts\static\Montserrat-Light.ttf" />
    <Resource Include="Fonts\static\Montserrat-LightItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-Medium.ttf" />
    <Resource Include="Fonts\static\Montserrat-MediumItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-Regular.ttf" />
    <Resource Include="Fonts\static\Montserrat-SemiBold.ttf" />
    <Resource Include="Fonts\static\Montserrat-SemiBoldItalic.ttf" />
    <Resource Include="Fonts\static\Montserrat-Thin.ttf" />
    <Resource Include="Fonts\static\Montserrat-ThinItalic.ttf" />
    <None Update="AppSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\reading.png" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.7.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.7.2 %28x86 i x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\336-3364653_x-button-exit-icon-symbol-sign-cross-botao.jpg" />
    <Resource Include="Images\arrow.png" />
    <Resource Include="Images\arrowchevron.png" />
    <Resource Include="Images\bg.jpg" />
    <Resource Include="Images\bg.png" />
    <Resource Include="Images\book.png" />
    <Resource Include="Images\duo.png" />
    <Resource Include="Images\eng_flag.png" />
    <Resource Include="Images\exit.png" />
    <Resource Include="Images\fr_flag.png" />
    <Resource Include="Images\ger_flag.png" />
    <Resource Include="Images\info.png" />
    <Resource Include="Images\lekcje.png" />
    <Resource Include="Images\lekcje2.png" />
    <Resource Include="Images\logout.png" />
    <Resource Include="Images\mainpage.png" />
    <Resource Include="Images\menu.png" />
    <Resource Include="Images\menu2.png" />
    <Resource Include="Images\settings.png" />
    <Resource Include="Images\slownik.jpg" />
    <Resource Include="Images\slownik.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Fonts\OFL.txt" />
    <Resource Include="Fonts\README.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\listening.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\listen.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.39.0" />
    <PackageReference Include="Azure.Identity" Version="1.11.2" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.6.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.18.0" />
    <PackageReference Include="Azure.Storage.Common" Version="12.17.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.5.1" />
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="2.3.2" />
    <PackageReference Include="Microsoft.Azure.KeyVault.WebKey" Version="2.0.7" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.0.3" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.37.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.24" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.60.3" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.60.3" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="6.35.0" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.14.2" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime.Azure" Version="3.3.19" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="MongoDB.Driver" Version="2.25.0" />
    <PackageReference Include="Syncfusion.Licensing" Version="22.2.9" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="22.2.9" />
    <PackageReference Include="System.ClientModel" Version="1.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Abstractions" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.IO.Hashing" Version="6.0.2" />
    <PackageReference Include="System.Memory.Data" Version="6.0.0" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="6.0.0" />
    <PackageReference Include="System.Speech" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AzureVaultKeyAccessProvider\AzureVaultKeyAccessProvider.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>